### ISSUE TITLE
Curseforge Related Dependencies are incorrect

### ISSUE THREAD

**Issue by Obbay2** [Szum123321/textile_backup#103]
https://www.curseforge.com/minecraft/mc-mods/textile-backup/relations/dependencies

Points at legacy Cloth Config API which makes Curseforge download:
- cloth-config-5.3.58-fabric.jar

Instead of the version used in the Gradle build:
- cloth-config-7.0.72-fabric.jar

Points at Mod Menu mod, however Curseforge doesn't download the mod at all

**Comment by Szum123321** [comment]
Thank you!
