### ISSUE TITLE
Server Java Error.

### ISSUE THREAD

**Issue by MrFreakOne** [Szum123321/textile_backup#105]
Hello, 

I've been trying to get my fabric server to work for over 8 hours, unfortunately without success. I've searched the internet for server backup alternatives, unfortunately without success. The problem is that my server stubbornly refuses, with the mod "textile_backup-2.2.0-1.16.jar" for version 1.16.5

I keep getting the same error message for hours and I don't know why. It says something about Java 11 or 16 I've tried both versions on my server. I changed it but it still refuses to start with this mod. I don't know what to do anymore, that's why I'm posting here in the forum and hoping for help.

Minecraft: 1.16.5
Fabric Loader v0.14.8
Java: 8/11/16  (all versions tested without success)
ModPack: Sky+FABRICation 2 v1.1.1a
Link: https://www.curseforge.com/minecraft/modpacks/sky-fabrication-2

Error Log: https://pastebin.com/WZnpXAxc

See You.

**Comment by Szum123321** [comment]
How do you start your server? It looks as though you actually hadn't updated java

**Comment by MrFreakOne** [comment]
Hello,  (Google Translator)

@Szum123321

it's a Nitrado server. In the options you can decide which Java version it should have, i.e. which one it should start with. I've tried every Java version. Without success, it does not start, when I deleted the mod "textile_backup" everything works great.

But we all know Minecraft all too well, without a backup on its server you're left, in case of an error your save data is lost, and days of gameplay along with it. Thanks for your answer. :)

Java: 8/11/16/17  (You can choose and save the version you want. The server then starts with this version.)

See You.  :)

**Comment by Szum123321** [comment]
You might try to update Fabric Loader perhaps. If that doesn't help, i can't really do much. You should contact your server provider in that case. Good luck

**Comment by MrFreakOne** [comment]
Hello,   (Google Translator)

@Szum123321

it has nothing to do with the fabric loader at all. (Fabric Loader v0.14.8) I have had the same server provider for over 2 years. My PC is strong enough, it's only 4 months old.

It's this buggy mod. Not a single mod causes problems with over 200 mods. It's this buggy mod. Not a single mod causes problems with over 200 mods. It's just this one mod that's screaming rum and not working properly. Well, thanks for your "not helping". 

Bye

**Comment by Szum123321** [comment]
I see you're upset but the error is thrown by the Fabric Loader, it clearly says you ran it with j11 not 16.

**Comment by MrFreakOne** [comment]
Hello,  (Google Translator)

@Szum123321

it's all ok. I deleted this ModPack. I don't have the nerve to spend days trying to make it work. Deleted it completely. I wanted to try Fabric because everyone thinks Fabric runs much better.

Fabric never again. I have already chosen another ModPack and uploaded it to my server. A Forge ModPack with over 300 mods, and lo and behold, no "single" problems. It's going well. Thanks for your answers. wish you all the best

###
**PS:** I have already mentioned that I always get the same error message with "every" Java version. As I mentioned, I don't see any difference, the error messages look the same to me. I've already said that I'm not a professional programmer. I ended up with a great many error messages about trying java's and more. I took some error message. It would be way too much, so I picked a random one. I hope you are still reading all of this!

Bye.
