### ISSUE TITLE
[1.19.2 BUG] Starting a backup crashes the server

### ISSUE THREAD

**Issue by FlashHUN** [Szum123321/textile_backup#108]
Running `/backup start` on a 1.19.2 server crashes it.

Fabric version: `0.14.9-1.19.2`
Fabric API version: `0.59.0+1.19.2`
Mod version: `2.4.0-1.19`

[Crash Report](https://pastebin.com/NAUBbc21)

**Comment by Szum123321** [comment]
Update to 2.4.0-1.19.1

**Comment by Szum123321** [comment]
For the record: Microsoft broke compatibility between 1.19 and 1.19.1. So TxB for 1.19 is only compatible with 1.19. TxB for 1.19.1 works with both 1.19.1 and 1.19.2.
