### ISSUE TITLE
Massive cache memory leak while taking a backup

### ISSUE THREAD

**Issue by JKM115** [Szum123321/textile_backup#113]
![image](https://user-images.githubusercontent.com/85696039/204857257-4d844882-3897-4e9a-b19f-4a299ecbe9dc.png)

While taking a backup with /backup start name command, the server tends to instantly eat as much (or nearly as much) cache as the world weighs. I'm using newest available 1.18.2 version of the mod 2.5.0

The 2 giant spikes of cache usage are me taking 2 backups 2 minutes apart. Cache usage jumps from 0.2GB to 6.8GB. The entire world takes up 7GB

**Comment by Szum123321** [comment]
Please define what do you mean by cache. If you mean the temporary directory of the system, then yes, that is the expected behavior
