### ISSUE TITLE
BZIP2 produces empty files after 1.20 (3.1.0) update

### ISSUE THREAD

**Issue by HorriblePerson555** [Szum123321/textile_backup#122]
Hey, I just updated my fabric server that I run for friends to 1.20. Before I used the BZIP2 compression, but it now only produces empty files. I have switched to GZIP which fixed the problem. Apart from that, everything works fine.

![image](https://github.com/Szum123321/textile_backup/assets/47578455/a001a33a-95f5-4ca2-93a7-ccdb487af24e)

Nothing weird in the server logs except no compression time:

![image](https://github.com/Szum123321/textile_backup/assets/47578455/80304eb8-3efe-4ffa-aab1-c953ee57aa5a)

I'm no expert at the inner workings of a Minecraft server, so I don't know what else to include here.

**Comment by Szum123321** [comment]
Issue confirmed. No error so far

**Comment by Szum123321** [comment]
fixed in 3.1.2
