### ISSUE TITLE
1.19.4 support?

### ISSUE THREAD

**Issue by Mailiax** [Szum123321/textile_backup#126]
As the title says, just wondering if there will be a version for 1.19.4 of this mod. Is there any specific reason for not providing a version for 1.19.4?

**Comment by Mailiax** [comment]
Realised just now that the 2.5.0-1.19 version on CurseForge says it's made for 1.19.1 - 1.19.4, but the same version on Modrinth only specifies 1.19.1 - 1.19.3. I guess that's a mistake?

**Comment by Szum123321** [comment]
yep, forgot to update release flags. in general, TxB stay compatible with the whole major release.
