### ISSUE TITLE
Server hangs on Waiting on world statistics

### ISSUE THREAD

**Issue by Aphyxia** [Szum123321/textile_backup#132]
Server hangs on backup. Server console outputs that it is waiting on world statistics.
After a while Server Watchdog sees that one tick took too long and closes the server, giving a, seemingly different every time, crashlog.

This started after visiting the End dimension for the first time.
Removing DIM-1 from the world folder seems to fix it.
Another random thing is that this does not happen every time the backup starts but it does happen more often than not. At least every second backup.

I'm guessing it would have to be the fault of recently updated entities or regions but as it stands I have no further way of debugging this.

The latest crashlog: https://pastebin.com/pbvuuRBd

Edit:
While it seemed to work fine for a while. It started the backup when everyone was offline (even though I have that setting turned off...) and hanged the same way while saving overworld. So I'm all out of ideas.

**Comment by Szum123321** [comment]
another case of #81. The server hangs up waiting for save to complete
