### ISSUE TITLE
Live backups not working?

### ISSUE THREAD

**Issue by xMathayus** [Szum123321/textile_backup#135]
As of today the backup only seems to work when shutting down the server. I have only updated 3 mods not sure if they conflict but I'm sure they don't.

Mods
(Bclib)
(Better End)
(Puzzle Lib)

And fabric api to -0.86 as I was on 0.85.

**Comment by xMathayus** [comment]
~Update~

Turns out another mod of mine updated (Immersive Portals) and textile backup doesnt work with it.

**Comment by Szum123321** [comment]
Probably #123 ?
