### ISSUE TITLE
Crashes in 1.20.4

### ISSUE THREAD

**Issue by Jayspek** [Szum123321/textile_backup#147]
Just updated my server to 1.20.4, textile backup crashes immediately after the world finishes loading on server startup. I'm testing without any other mods (except fabric API and cloth config which are required).

Textile backup versions 3.1.2
Fabric loader 0.15.2
Fabric API 0.91.2
Cloth config 13.0.114

Log file and crash report are attached.

Any insight would be great!
[latest.log](https://github.com/Szum123321/textile_backup/files/13690690/latest.log)
[crash-2023-12-15_15.45.42-server.txt](https://github.com/Szum123321/textile_backup/files/13690693/crash-2023-12-15_15.45.42-server.txt)

**Comment by Szum123321** [comment]
1.20.4 isn't yet supported

**Comment by Szum123321** [comment]
Now it is.

**Comment by Jayspek** [comment]
Still getting the identical error with the new version

**Comment by aking4125** [comment]
Yep, same problem here:
[crash-2023-12-18_09.46.54-server.txt](https://github.com/Szum123321/textile_backup/files/13705202/crash-2023-12-18_09.46.54-server.txt)
[latest.log](https://github.com/Szum123321/textile_backup/files/13705204/latest.log)

**Comment by vizitys** [comment]
Yup, happening to me as well

**Comment by garpunkal** [comment]
And me. Patiently waiting for a fix

**Comment by Szum123321** [comment]
Should be fixed in 3.1.3
