### ISSUE TITLE
The server can't be stopped!

### ISSUE THREAD

**Issue by abwuge** [Szum123321/textile_backup#152]
Minecraft version: 1.20.4
Mod version: 3.1.3

在服务端使用stop命令，服务器会在执行完毕后卡在最后一步，必须强行停止，已确认是加上本mod而导致的，但不确定是否为mods冲突导致。
If the stop command is used on the server side, the server will be stuck in the last step after the execution is completed, and must be forced to stop. It has been confirmed that it is caused by adding this mod, but it is not sure whether it is caused by mod conflict.
使用mcsm ([MCSManager](https://github.com/MCSManager/MCSManager))作为面板控制端，mod列表如下：
Using mcsm ([MCSManager](https://github.com/MCSManager/MCSManager)) as the panel control, the list of mods is as follows:
```
$ ls Minecraft/mods/
ChatImage-1.2.2+1.20.4+fabric.jar                     gugle-carpet-addition-2.7.0-1.20.4.jar
Jade-1.20.4-fabric-13.2.1.jar                         krypton-0.2.6.jar
LuckPerms-Fabric-5.4.113.jar                          lazydfu-0.1.3.jar
McBot-fabric-2.2.1.1.jar                              lithium-fabric-mc1.20.4-0.12.1.jar
PluslsCarpetAddition-1.20.4-0.3.190+9e97daa-beta.jar  luckperms
appleskin-neoforge-mc1.20.4-2.5.1.jar                 magiclib-all-0.7.398+fe2125a-stable.jar
c2me-fabric-mc1.20.4-0.2.0+alpha.11.56.jar            servux-fabric-1.20.2-0.1.0.jar
cloth-config-13.0.121-fabric.jar                      skin-restorer-1.2.4.jar
fabric-api-0.96.4+1.20.4.jar                          syncmatica-1.20.2-0.3.11.jar
fabric-carpet-1.20.3-1.4.128+v231205.jar              textile_backup-3.1.3-1.20.jar
floodgate-fabric-2.2.0-SNAPSHOT+build.17.jar          vanilla-permissions-0.2.3+1.20.4.jar
geyser-fabric-2.2.2-SNAPSHOT+build.469.jar
```
由于这并不是崩溃，所以我认为logs文件无需提供，如果需要，我会在回复中上传。
Since this is not a crash, I don't think the logs file needs to be provided, and I will upload it in my reply if necessary.

**Comment by Szum123321** [comment]
If you're using GZIP then it's #37
