### ISSUE TITLE
Lost my backup

### ISSUE THREAD

**Issue by JJAAMMes** [Szum123321/textile_backup#157]
Not exactly a technical issue, when max size of backup is saved and the most previous backup is restored with the backup old world turned on, the old-world backup will replace the most previous backup, so it's deleted and cannot be loaded :(

**Comment by JJAAMMes** [comment]
probably should add a warning or something when restoring a backup because you won't expect the backup you're trying to restore to be deleted right after you run the command...

**Comment by ARedstoneMan** [comment]
Same issue here. This seems very counter-intuitive as you would expect the oldest backup to be deleted, not the one you are trying to load. As a more technical player, I want to be able to go back to the same backup multiple times if I mess something up, so it would be helpful if the deletion would prioritize the oldest backup no matter how new backups are created.

**Comment by Szum123321** [comment]
RTFM, there's literally an option to do so and it's more than 3 years old. `deleteOldBackupAfterRestore`. With newer versions the just restored zip file only gets deleted if the restoration succeeds. 

On more personal note, i think this is a very reasonable behavior, once a backup is unpacked without any errors, the exact state of the world is present in the game folder. There's little need to keep an exact copy except zipped.
