### ISSUE TITLE
Error Time Format

### ISSUE THREAD

**Issue by NoNamedTV** [Szum123321/textile_backup#16]
Hello, I'm having troubles setting up the mod, because it send me the next error:
Exception in thread "Thread-67" [15:57:57] [Thread-67/INFO]: [STDERR]: java.nio.file.InvalidPathException: Illegal char <:> at index 13: 28.05.2020_15:57:57.zip
I tried to change the time format to solve the problem, but i didn't found it. Could you help me to solve it?

**Comment by Szum123321** [comment]
Which version are you using? What operating system are you using? Also you can change datetime format in the config file (textile_backup.json5) inside config folder.

**Comment by NoNamedTV** [comment]
im using minecraft 1.15.2 in win10 proN

**Comment by Szum123321** [comment]
All right, that seems right, but which version of the mod are you using?

**Comment by NoNamedTV** [comment]
1.0.1

**Comment by Szum123321** [comment]
That explains a lot. I would suggest you to update to newest version (1.2.1) as this, I think, exact problem was repaired in 1.0.2.

Pleas tell me your results.

**Comment by NoNamedTV** [comment]
okay ill try it thnx
btw do you have the dowload link?

**Comment by Szum123321** [comment]
https://www.curseforge.com/minecraft/mc-mods/textile-backup/files/2965528

**Comment by NoNamedTV** [comment]
thnx

**Comment by Szum123321** [comment]
Closing.
