### ISSUE TITLE
World session lock is released before backup has finished

### ISSUE THREAD

**Issue by mk-pmb** [Szum123321/textile_backup#161]
Hi, thank you for this nifty mod!
I noticed that Minecraft releases its world session lock (`…/saves/WORLD_NAME/session.lock`) while Textile Backup is still busy creating its shutdown backup. In theory, when you run multiple instances of Minecraft, this could allow a second instance opening the world while the first instance is still backing it up.
Can you make Minecraft wait, so it releases the session lock only after the backup is done?

**Comment by Szum123321** [comment]
I believe this to be an extremely unlikely scenario. Unless you can show that is causes some real issues, I won't be chasing this bug. You're welcome to open a pull request with a fix.
