### ISSUE TITLE
1.16 Pre5-Pre7 java io error due to locked file during compression

### ISSUE THREAD

**Issue by Linguardium** [Szum123321/textile_backup#18]
`The process cannot access the file because another process has locked a portion of the file`
https://hastebin.com/otuxukoguh.css

Did not test previous minecraft versions.

**Comment by Szum123321** [comment]
That's most likely because of changes from pre2 to pre7. I'll update soon.

**Comment by Szum123321** [comment]
Hi! It seems like this error is still there. Could you please tell me what os are you using?

**Comment by Linguardium** [comment]
Windows 10

reading the other issue report, it could be an issue with the compression engine used by default. Does the compression engine attempt to open the files read/write instead of read only?

**Comment by Szum123321** [comment]
Repaired in 3e17a6471406e0f5aa724d372192f74be3ce9468.

Thank you for reporting this bug.
