### ISSUE TITLE
Please consider adding Fabric API as a pre-requisite on your CurseForge page. 

### ISSUE THREAD

**Issue by onkoe** [Szum123321/textile_backup#19]
Currently, the requirement of Fabric API is not mentioned anywhere on the CurseForge page. As such, I spent around 30 minutes messing with plugins and testing compatibility before realizing that it might be required. I would hate for another (no-so-bright) user to have the same mistake. Thanks for the great plugin, by the way!

**Comment by Szum123321** [comment]
Done.
