### ISSUE TITLE
1.16.1 Backup Files are 1 KB

### ISSUE THREAD

**Issue by BarbarianMatt** [Szum123321/textile_backup#20]
Every time the server attempts a backup, the resulting file is 1 KB. It also says this error message right before it finishes compression: java.io.IOException: The process cannot access the file because another process has locked a portion of the file

**Comment by Szum123321** [comment]
Ok, it seems to be the  same as #18 . Could you tell me exactly, what operation system, what other mods (including versions) and which minecraft version are you using? Also how big is your minecraft world and please provide config file.

**Comment by BarbarianMatt** [comment]
Using Fabric 1.16.1, I just tested it with no other mods, and the error still happened. Running windows 10 pro. The minecraft world is 30.1 MB. Here is the link of the pastebin of the config file, but it is just the default settings: https://pastebin.com/Jcd2wSEx

**Comment by Szum123321** [comment]
Have you tried using different compression method?

**Comment by Szum123321** [comment]
Also is there anything other printed out after "java.io.IOException: The process cannot access the file because another process has locked a portion of the file"?

**Comment by BarbarianMatt** [comment]
There was no line of significance printed after the java.io error. I tested the other compression types and they had a similar-looking error message before the compression finished:  [Thread-58/ERROR]: [TextileBackup]: The process cannot access the file because another process has locked a portion of the file 

However, for the other compression types, the backup files were successful and not just 1 KB.

**Comment by Szum123321** [comment]
It seems to be windows thing. I will try to debug it further tommorwo.

**Comment by Szum123321** [comment]
I've successfully reproduced the bug so now I should be able to find its source.

**Comment by Szum123321** [comment]
So error happens when trying to compress a file called "session.lock". Until I find a better solution you can just exclude the file by adding it to the file blacklist (in the config) like this: 
```json
"fileBlacklist": [
        "session.lock"
	],
```

**Comment by Szum123321** [comment]
Repaired in 3e17a6471406e0f5aa724d372192f74be3ce9468. Updated version should be available on curseforge soon.

Thank you for reporting this bug.
See you!
