### ISSUE TITLE
With default filename format and backupsToKeep set, newest file is deleted after month rollover

### ISSUE THREAD

**Issue by LevelZero-dev** [Szum123321/textile_backup#22]
I have textile backup running on my server and noticed today that I didn't have any backup files after june 30.

Further checks revealed that backups were still being made, but were immediately deleted:
[17:15:14] [Server thread/INFO]: [TextileBackup]: Backup started by: SERVER on: 09.07.2020_17-15-14
[17:15:14] [Server thread/INFO]: [TextileBackup]: Saving server...
[17:15:14] [Thread-4192/INFO]: [TextileBackup]: Starting compression...
[17:15:18] [Thread-4192/INFO]: [TextileBackup]: Compression took: 4.292876443s
[17:15:18] [Thread-4192/INFO]: [TextileBackup]: Deleting: 09.07.2020_17-15-14.zip
[17:15:18] [Thread-4192/INFO]: [TextileBackup]: Done!

I have set backupsToKeep to 10 and there were exactly 10 files. However, due to the default filename format being used, the 09.07.2020_17-15-14.zip file comes up before the 30.06.2020_23-35-23.zip in the list, which means it deletes the new file just created instead of the older files.

Fix: Change the default time format in the config file from dd.MM.yyyy_HH-mm-ss to yyyy.MM.dd_HH-mm-ss

**Comment by Szum123321** [comment]
Oh! How could I have missed that! Thank you! Files are now just sorted in lexonographic order, so 01.09.2020_12-34-45 is "older" than 31.08.2020_12-34-45. I will first parse filename and that sort based on date&time. Please keep in mind that this format is configurable so someone could change it back.

**Comment by Szum123321** [comment]
I'll most likely repair it today.

**Comment by vkorn** [comment]
Was literally looking into the code right now. Ended up just making a simple comparator 

```
public class BackupComparator implements Comparator<File> {
    @Override
    public int compare(File o1, File o2) {
        return Long.compare(getTime(o1), getTime(o2));
    }

    private static long getTime(File f) {
        return LocalDateTime.from(
                Utilities.getDateTimeFormatter().parse(
                        f.getName().split(Objects.requireNonNull(BackupHelper.getFileExtension(f)))[0].split("#")[0]
                )
        ).toEpochSecond(ZoneOffset.UTC);
    }
}

```

to use at arrays.sort https://github.com/Szum123321/textile_backup/blob/stable/src/main/java/net/szum123321/textile_backup/core/BackupHelper.java#L115

**Comment by Szum123321** [comment]
That would work (partially, remember that there is also a backup formatter), but I have already rewritten this part of the code, so I think I'm going to stick to my solution. Gimme a moment to test everything.

**Comment by Szum123321** [comment]
Should be repaired in 422d3fcd2f16ae6b3f6b16302082f39f68d85a2c. Now i will test everything. If you have any suggestions, or comments, please tell me.

**Comment by Szum123321** [comment]
All right, few small things repaired.

**Comment by Szum123321** [comment]
https://www.curseforge.com/minecraft/mc-mods/textile-backup/files/3000598

https://github.com/Szum123321/textile_backup/releases/tag/1.2.4
