### ISSUE TITLE
Use a sortable time format as the default filename format.

### ISSUE THREAD

**Issue by expeehaa** [Szum123321/textile_backup#25]
With the current default filename format (dd.MM.yyyy_HH-mm-ss), it is not possible to easily sort the backups by date.
Though this is configurable, it might be useful to replace this format with a one like "yyyy-MM-dd_HH-mm-ss", which can be sorted simply by ordering the filename strings.

**Comment by Szum123321** [comment]
I does not matter. I've already implemented much more robust system an now such change would break more stuff. Also remember that time format is configurable.
