### ISSUE TITLE
Consider not starting a backup when the first user joins after starting the server.

### ISSUE THREAD

**Issue by expeehaa** [Szum123321/textile_backup#27]
Backing up the world is a performance-hungry task for bigger worlds. In my case, the world currently has a size of a 1GB.
Whenever a backup is started, the server is lagging a bit for around 35s, until the backup is done.
When the server is (re-)started and the first user joins, this mod will back up the world. Since nothing can/should have happened since the start, this backup seems to be kind of useless.
This is especially annoying when repeatedly restarting a server to try out new configurations.

It would be great if a backup is first attempted after the backup interval time ran out after the first user joined, or if a config option for such a behaviour would be provided.

**Comment by Szum123321** [comment]
Yeah, that would work. I should have spent more time working on scheduler when first writing it. I will implement such changes soon.

**Comment by Szum123321** [comment]
Implemented in #28
