### ISSUE TITLE
[Feature Request] Backup after player logout

### ISSUE THREAD

**Issue by Tsudico** [Szum123321/textile_backup#3]
There currently is a setting for backup only if a player is in world. If a player logs out just prior to the next backup no backup is done. It would be nice if a check is done when players log out to determine if any players are on the server and if not to do a backup.

**Comment by Szum123321** [comment]
I may take a look at this in few days

**Comment by Szum123321** [comment]
Actually I don't think is really necessary.

**Comment by Szum123321** [comment]
Implemented in #28
