### ISSUE TITLE
Out of space error when there is enough space

### ISSUE THREAD

**Issue by matthew-salerno** [Szum123321/textile_backup#31]
Hello, I'm not sure if this is your fault or mine, but I'm running in a containerized linux system with a snap I'm making called mc-service, which runs minecraft as a containerized daemon and listens for commands from mc-manager to control it.
My issue is this, during backup (I have a large pregenerated world of about 7.7GB) I get this error:
[crash.txt](https://github.com/Szum123321/textile_backup/files/4974869/crash.txt)
What's weird about this is I have the server folder mounted to a 1TB hard drive, my 7.7G world shouldn't put a dent in this.
I have tried this twice, and both resulting backup files were 4.0K
I wouldn't be surprised if the issue was on my end, but I'm not familiar with java and would love some ideas on where to look if this is due to my environment and not an issue with backing up large worlds.
Thanks!

**Comment by Szum123321** [comment]
Hi! 
Sadly, that's known problem with zip compressor. For now, try using different compressor such as bzip2 or gzip. 
Sorry!

**Comment by matthew-salerno** [comment]
Not a problem, GZIP works fine. Thanks!
