### ISSUE TITLE
Feature Request: world edit compatibility 

### ISSUE THREAD

**Issue by ttamttamS** [Szum123321/textile_backup#35]
So I found an issue where worldedit expects files (for snapshots) in the format of "backup/world/<time>/world" or "backup/<time>/world". Currently textile stores backups as "backup/world/<time>" or "backup/<time>".
Could there be an option to store backups in the previous (world edit) formats?
Otherwise this mod should work fine with world edit with just a few config changes.

**Comment by Szum123321** [comment]
You can always change that in the config

**Comment by SusStew** [comment]
> You can always change that in the config

As far as I can tell, this can not actually be changed. See EngineHub/WorldEdit#2376
