### ISSUE TITLE
backups don't complete if single-player client exits game

### ISSUE THREAD

**Issue by pcal43** [Szum123321/textile_backup#36]
Hi.  Thanks very much for writing this mod - it's very useful and works really well.

I'm using it on a single-player setup (no server) and configured it to do a backup on world shutdown.  This works great with one minor issue: if the user quits the minecraft app before the backup is finished, the backup is aborted and an empty file is saved.

Ideally, the backup thread would be allowed to complete before the vm shuts down.  But I realize you may not actually be able to do anything about this it if (for example) minecraft is doing a System.exit (I don't know what it does). 

In any event, thanks again for the great mod!

**Comment by Szum123321** [comment]
I'm quite certain that there isn't much that I can do. 

Sorry!

**Comment by pcal43** [comment]
Understood.  Thanks again!
