### ISSUE TITLE
Backup location confusion

### ISSUE THREAD

**Issue by tayctl** [Szum123321/textile_backup#39]
Hello,

I have recently download Textile Backup ver. 1.4.0 for 1.16.1.
Everything works great, but I can't seem to change the backup location, at first I tried to back up to my D drive as it has more capacity, but it wouldn't work. 
After this, I tried chaning it to a folder on my desktop, but to no avail.
For backing up to my d drive I wrote `"path": "D:\Minecraft-Server-Backup\Vanilla",` but when I open the config file after shutting the server down it changed to `"path": "D:Minecraft-Server-BackupVanilla",`.
The same happened when I tried to backup to my C drive.

I don't know if it is relevant, but the server is 1.16.1 and runs the following mods:
- Fabric API (ver. 0.18.0, build 387)
- Malilib Fabric (ver. 0.10.0 dev. 21)
- Fabric Carpet (ver. 1.4.0)
- Carpet Extra (ver. 1.4.0)
- Phosphor Fabric (ver. 0.6.0)
- Lithium Frabric (ver. 0.5.0)
- Minihud Fabric (ver. 0.19.0)
- Textile Backup (ver. 1.4.0)

**Comment by Szum123321** [comment]
Hi!
Have you tried using double back slash after C:?

**Comment by tayctl** [comment]
I will try that and get back to you with the result
Edit: it works, thank you for the help :)

**Comment by Szum123321** [comment]
Great!
