### ISSUE TITLE
backupsToKeep setting doesn't seem to work

### ISSUE THREAD

**Issue by Zevac-ZSF** [Szum123321/textile_backup#4]
Hi I'm using textile_backup-1.0.2-1.15.2 and have backupsToKeep=48 (maxAge=0), but older backups (more then 48) are not cleaned up.

Can you have a look at it?

Thanx in Advance

Z.
[textile_backup.json5.txt](https://github.com/Szum123321/textile_backup/files/4254889/textile_backup.json5.txt)

**Comment by Szum123321** [comment]
One thing that you seem to have missed is that this mod uses relative path to backup folder. and this folder have to be located within game folder. Not on other drive.

**Comment by Szum123321** [comment]
Now absolute paths should work in 1.0.3

**Comment by Zevac-ZSF** [comment]
Perfect, thanx for the quick fix!!!
