### ISSUE TITLE
[Feature Request 功能请求]Add a command to delete unwanted backups.  希望可以添加一个子命令来删除不需要的备份

### ISSUE THREAD

**Issue by Harveykang** [Szum123321/textile_backup#43]

**Comment by Harveykang** [comment]
by the way:
/backup start "这是一个例子"
There is no Quotation marks in README_zh-CN.md. 中文自述文件中这里没有加引号

**Comment by Szum123321** [comment]
Can you make a pr?

**Comment by Harveykang** [comment]
might works like this:
/backup delete [DATE_TIME]
sometimes I made lots of backup in one hour, but I just want to keep the latest one

**Comment by Szum123321** [comment]
Oh, sorry, I have only read your last comment I immediately responded to it. 
So about the delete command, it sounds good, I might add it

**Comment by Harveykang** [comment]
It's a bit slow to connect to GitHub in China. So I may not be able to reply immediately.
For README_zh-CN.md, should be like this:
![image](https://user-images.githubusercontent.com/46108547/100113815-b2dc4f00-2eab-11eb-8b56-67c6ce039afc.png)
cannot enter Chinese without quotation marks:
![image](https://user-images.githubusercontent.com/46108547/100113923-d2737780-2eab-11eb-8488-eca279f8da69.png)

**Comment by Harveykang** [comment]
thank you so much, great mod, btw^^

**Comment by Szum123321** [comment]
Alright, i'll leave this issue here, so that I won't forget it.

**Comment by Szum123321** [comment]
Closed in 7f82664ae7c80aa1249285e004981c6b39316cef
