### ISSUE TITLE
[Feature Request]Use global messages instead of private chat messages during backup and restore

### ISSUE THREAD

**Issue by Harveykang** [Szum123321/textile_backup#48]
![image](https://user-images.githubusercontent.com/46108547/100163710-3d936d00-2ef1-11eb-9590-80b3eba4cca8.png)
other players cannot see these messages
if they can, it will avoid the trouble caused by using large machine during backup
or they can get a warning when restoring the world

**Comment by Szum123321** [comment]
Yes, I have that on my todo list

**Comment by Szum123321** [comment]
Closed in 2a211065a39ec603ad1b9f532b686bec27a44c4c
Will be available in 2.1.0
