### ISSUE TITLE
Cannot Restore From Old Backups After Changing DateTime Format

### ISSUE THREAD

**Issue by jessiewestlake** [Szum123321/textile_backup#50]
|File|Version|
|---|---|
|Minecraft|1.16.4|
|Fabric API|0.27.1+1.16|
|Textile Backup|2.0.1-1.16.3|

I made many backups with the default datetime format `dd-MM-yyyy_HH.mm.ss`, but I recently changed the datetime format to `yyyy-MM-dd_HH.mm.ss` and now I cannot restore from any backup made with the old datetime format; even ones made earlier in the day before the change.

I receive an error stating that there is no such backup created at that time, even though I'm using the tab autocomplete to select the file. Any backups made after the format change can be restored from just fine.

````
/backup list

[Textile Backup] Available backups:
2020-12-02_09.50.15#shutdown,
2020-12-02_09.57.24#shutdown,
2020-12-02_10.01.21#shutdown,
2020-12-02_10.25.48#shutdown,
2020-12-05_04.59.10#shutdown,
2020-12-06_02.18.53#shutdown,
2020-12-08_16.40.19#shutdown,
2020-12-08_18.21.55,
2020-12-08_18.24.11#shutdown,
2020-12-08_18.30.05#shutdown
````
````
/backup restore 2020-12-02_09.50.15

[Textile Backup] No file created on 2020-12-02_09.50.15 was found!
````

**Comment by Szum123321** [comment]
That is not a bug, rather the price I paid for ability to change the format. The mod always tries parsing the the backup name, bu if you have changed it, the mod really doesn't know to do it, so it gives up on that file.

**Comment by Szum123321** [comment]
Like, just chanhe to the old format, commands use ISO anyways.
