### ISSUE TITLE
Backup process takes longer than needed

### ISSUE THREAD

**Issue by supsm** [Szum123321/textile_backup#53]
I see that there are a few things that could be optimized. First, using the `save-all` command would probably be faster than what is currently implemented.
![image](https://user-images.githubusercontent.com/60897356/103445167-d2dafd00-4c25-11eb-9121-abd618c79935.png)
![image](https://user-images.githubusercontent.com/60897356/103445181-fdc55100-4c25-11eb-98ce-d46f33d74582.png)
I'm using this screenshot as the example since it actually shows the ThreadedAnvilChunkStorage message. However, backups sometimes can last 20 seconds, and once it lasted more than 60 (which crashed my server). From the second image, you can see that running `save-all` takes less than 1 second. Other backup mods, such as [AutoBackup](https://github.com/sefodopo/FabricAutoBackup) use `save-all`, but I prefer this mod because setup is simpler and I can restore backups more easily.

Another possible optimization I see is that some people might not want their backups to actually be compressed. I have my compression level set to 0, but it still takes 1-2 seconds for compression. Maybe add an option for the format to be `NONE`? It seems that the compression process doesn't actually affect the server, but I thought it might be easier for some people this way.

**Comment by Szum123321** [comment]
Actually both AutoBakcup and Textile Backup save the server in exactly the same way. We both use code taken from /save-all command.

See: 
https://github.com/Szum123321/textile_backup/blob/acba0d0cb82dfdd522ca29d3e69dffe2e1eaed90/src/main/java/net/szum123321/textile_backup/core/create/BackupHelper.java#L66-L70

https://github.com/sefodopo/FabricAutoBackup/blob/5ef2e542d862b53bc77f0474468e30ebef6ae091/src/main/java/com/sefodopo/autobackup/Backup.java#L60-L62

**Comment by Szum123321** [comment]
Sorry, I forgot about the feature request. I'll keep it in mind.

**Comment by Szum123321** [comment]
3c5976f19830f2a0c216b9ac99ad82c7acc92726 should solve it.

**Comment by supsm** [comment]
Thanks, I just thought it took longer than running the save-all command manually.

**Comment by supsm** [comment]
May I ask what the parameters for `save()` are? I've noticed in AutoBackup that it uses `save(true, true, true)`, whereas in textile backup it uses `save(false, true, true)`
