### ISSUE TITLE
[bug] unable to decompress the files supplied by mods correctly

### ISSUE THREAD

**Issue by Harveykang** [Szum123321/textile_backup#56]
![image](https://user-images.githubusercontent.com/46108547/104113553-b78d8300-52f2-11eb-9107-3f168525cca7.png)
![image](https://user-images.githubusercontent.com/46108547/104113560-c5db9f00-52f2-11eb-8742-214bd103ae58.png)
there should be some files in this folder, but it's empty after restore

**Comment by Szum123321** [comment]
I'll look into it

**Comment by Harveykang** [comment]
> I'll look into it

thank you ^_^

**Comment by Szum123321** [comment]
May I ask what mod adds those scripts?

**Comment by Harveykang** [comment]
https://github.com/gnembon/fabric-carpet
this one

**Comment by Harveykang** [comment]
this mod supplies a script language, similar to datapack in vanilla

**Comment by Harveykang** [comment]
check this...
https://github.com/FZ-Studio/textile_backup/commit/9518ef9c76e60ce0bf7cd7c6fe5458577020329d
just don't delete directories
idk why cannot delete the directory..

**Comment by Szum123321** [comment]
It should be more like this:

```java
        boolean state = true;

        if(f.isDirectory()) {
            for(File f2 : f.listFiles()) state &= deleteDirectory(f2);
        }

        return (f.isDirectory() ? true : f.delete()) && state;
```

Although I can't see how that would work...

The only reason I can think of right now i that maybe those files where somehow write protected. If so have you seen a message saying `Something went wrong while deleting old world!` ?

**Comment by Harveykang** [comment]
i saw that message. but the folder was actually deleted.
then the carpet mod will create an empty “scripts” folder on server started.

**Comment by Szum123321** [comment]
huh. I suppose that maybe some part of the file gets left which makes it later impossible to restore them...

https://github.com/Szum123321/textile_backup/tree/56-bugfix 

Here's a branch where I made it so that files that weren't deleted get logged.
Do you know how to build fabric mod?

**Comment by Harveykang** [comment]
yeah i know

**Comment by Harveykang** [comment]
![image](https://user-images.githubusercontent.com/46108547/105609121-03cecd80-5d9f-11eb-8d26-409f16099ee0.png)

what the hell..

**Comment by Szum123321** [comment]
Well, the game fails to create scripts folder and so the scripts don't get decompressed. Can you check if the folder is write-protected or something?

**Comment by Szum123321** [comment]
ok I just found a way to tell exactly what went wrong. Give me a moment, and I'll commit changes to that branch

**Comment by Harveykang** [comment]
ok
btw, the folder has no write-protection

**Comment by Szum123321** [comment]
ok. See 011283dc094e2380e350914b7532c264e745d3f5 Files.createDirectories throws and exception if something goes wrong

**Comment by Harveykang** [comment]
[01:55:18] [Textile Backup restore thread nr. 0/ERROR] (textile_backup) [Textile Backup] An exception occurred when trying to create .\world\scripts\here.sc
java.nio.file.AccessDeniedException: E:\VSCode Projects\textile_backup-56-bugfix\run\.\world\scripts
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at net.szum123321.textile_backup.core.restore.decompressors.ZipDecompressor.decompress(ZipDecompressor.java:61) [textile_backup-2.1.0-prev-1.16-dev.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at net.szum123321.textile_backup.core.restore.RestoreBackupRunnable.run(RestoreBackupRunnable.java:78) [textile_backup-2.1.0-prev-1.16-dev.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[01:55:18] [Textile Backup restore thread nr. 0/ERROR] (textile_backup) [Textile Backup] An exception occurred while trying to decompress file: here.sc
java.nio.file.AccessDeniedException: .\world\scripts\here.sc
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_181]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at net.szum123321.textile_backup.core.restore.decompressors.ZipDecompressor.decompress(ZipDecompressor.java:66) [textile_backup-2.1.0-prev-1.16-dev.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at net.szum123321.textile_backup.core.restore.RestoreBackupRunnable.run(RestoreBackupRunnable.java:78) [textile_backup-2.1.0-prev-1.16-dev.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by Harveykang** [comment]
it's 2 a.m. in china, i have to go to sleep. 
if there is any problem, i'll reply tomorrow :)
