### ISSUE TITLE
Feature Request: Message when backup is finished

### ISSUE THREAD

**Issue by supsm** [Szum123321/textile_backup#58]
There is a mod that says when the backup starts, but could we have a config option for another message when it ends? Maybe an option for when the server has finished saving (since players cannot interact with the server while it's saving), and another one for when the entire backup (compression) finishes.

**Comment by Szum123321** [comment]
Added with 51330a036d8768a6f6587ecaeec7f29b81f4e2bb and eb6f4fdb10490a467eff66d158471bbd49150a1a
