### ISSUE TITLE
1.0.4-1.15 requires MC 1.16.*

### ISSUE THREAD

**Issue by OliverDudgeon** [Szum123321/textile_backup#6]
When I run a Fabric Server with textile_backup-1.0.4-1.15.jar and latest fabric-api the server fails to start with
```Could not find required mod: textile_backup requires {minecraft @ [1.16.*]}```

I'm using

- fabric-installer-0.5.2.39.jar
- fabric-api-0.5.1+build.294-1.15.jar
- textile_backup-1.0.4-1.15.jar

**Comment by Szum123321** [comment]
I must have forgotten to change targeted version. Give me a second.

**Comment by Szum123321** [comment]
Done. The correct version is now available on curseforge under the same name.
