### ISSUE TITLE
Fabric 1.16.5 backups are still made when no players are online

### ISSUE THREAD

**Issue by SirWoofie** [Szum123321/textile_backup#60]
/* 
Should backups be done even if there are no players?
*/
"doBackupsOnEmptyServer": false,

And yet backups are still being made when 0 players are online. Left the server up for 10 hours overnight (checked logs, nobody was ever on) and my backups folder contains those backups (and only those backups because I have the mod set to delete the 11th oldest backup).
The server is running a handful of server-only mods so vanilla clients can still join.
If there's anything else I can do to help figure out this issue, I'll try to help!

**Comment by Szum123321** [comment]
can you tell me more about your configuration? I'm not currently able to reproduce the bug.

**Comment by SirWoofie** [comment]
here is the most recent startup so you can see what all I've got running. https://paste.ee/p/WtR8M

**Comment by Szum123321** [comment]
Probably misinterpreted intended behaviour
