### ISSUE TITLE
when i restore,my whole save was delete and became to it's origin ???????

### ISSUE THREAD

**Issue by Tenktau** [Szum123321/textile_backup#61]
first,i used"backup start",then it told me that job is done.
second,i tried"backup restore",then after 30s,the server reload,when i log in,my whole save was gone.....
can you help me with that?

**Comment by Szum123321** [comment]
Are you sure you have restored the correct file?

**Comment by Tenktau** [comment]
I'm sorry that I forgot to reply u ,and now I don't really remember what happened at that time, so I close this issue now... SORRY AGAIN! :)
