### ISSUE TITLE
Backup on Shutdown

### ISSUE THREAD

**Issue by The-Peck** [Szum123321/textile_backup#62]
When I have the Backup on Shutdown true it attempts a backup but always ends up being a 0 file size. I'm running this on a server host, MCPH, so it might be something where they won't allow it to backup before it shuts everything down.

I've turned it off but here my config file:

> {
	/* 
	   Time between automatic backups in seconds
	   When set to 0 backups will not be performed automatically
	*/
	"backupInterval": 86400,
	/* 
	   Delay in seconds between typing-in /backup restore and it actually starting
	*/
	"restoreDelay": 30,
	/* 
	   Should backups be done even if there are no players?
	*/
	"doBackupsOnEmptyServer": false,
	/* 
	   Should backup be made on server shutdown?
	*/
	"shutdownBackup": false,
	/* 
	   Should world be backed up before restoring a backup?
	*/
	"backupOldWorlds": true,
	/* 
	   Should every world have its own backup folder?
	*/
	"perWorldBackup": true,
	/* 
	   A path to the backup folder
	*/
	"path": "backup/",
	/* 
	   This setting allows you to exclude files form being backedup.
	   Be very careful when setting it, as it is easy corrupt your world!
	*/
	"fileBlacklist": [],
	/* 
	   Should backups be deleted after being restored?
	*/
	"deleteOldBackupAfterRestore": true,
	/* 
	   Maximum number of backups to keep. If set to 0 then no backup will be deleted based their amount
	*/
	"backupsToKeep": 3,
	/* 
	   Maximum age of backups to keep in seconds.
	    If set to 0 then backups will not be deleted based their age 
	*/
	"maxAge": 0,
	/* 
	   Maximum size of backup folder in kilo bytes (1024).
	   If set to 0 then backups will not be deleted
	*/
	"maxSize": 0,
	/* 
	   Compression level 
	   0 - 9
	    Only affects zip compression.
	*/
	"compression": 7,
	/* 
	   Limit how many cores can be used for compression.
	   0 means that all available cores will be used
	*/
	"compressionCoreCountLimit": 0,
	/* 
	   Available formats are:
	   ZIP - normal zip archive using standard deflate compression
	   GZIP - tar.gz using gzip compression
	   BZIP2 - tar.bz2 archive using bzip2 compression
	   LZMA - tar.xz using lzma compression
	*/
	"format": "ZIP",
	/* 
	   Minimal permission level required to run commands
	*/
	"permissionLevel": 4,
	/* 
	   Player on singleplayer is always allowed to run command. Warning! On lan party everyone will be allowed to run it.
	*/
	"alwaysSingleplayerAllowed": true,
	/* 
	   Players allowed to run backup commands without sufficient permission level
	*/
	"playerWhitelist": [Gazel],
	/* 
	   Players banned from running backup commands besides their sufficient permission level
	*/
	"playerBlacklist": [],
	/* 
	   Format of date&time used to name backup files.
	   Remember not to use '#' symbol or any other character that is not allowed by your operating system such as:
	   ':', '\', etc...
	   For more info: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
	*/
	"dateTimeFormat": "yyyy.MM.dd_HH-mm-ss"
}

**Comment by Szum123321** [comment]
Can you share your server logs?

**Comment by Szum123321** [comment]
Closing due to lack on activity
