### ISSUE TITLE
Feature Request: Incremental Backups

### ISSUE THREAD

**Issue by ZBlackw1** [Szum123321/textile_backup#66]
Hey there, First of all, thanks for the great mod. It works very well. However, the one thing I can think of that would make it better is Incremental backups. My server is hosted so I have limited disk space. This means I can only keep one or 2 backups before I run out of space. The ability to have incremental backups of only the files changed would be a huge help to disk space management. Ideally, you would have the ability to set a schedule and retention policy for both full and Incremental backups. ie. Incremental backups every hour and keep them for a week and a full backup once a week and keep the last 2. Let me know if you have any questions.

**Comment by Szum123321** [comment]
Duplicate #10

**Comment by Szum123321** [comment]
I dont have the time to develop such a complex feature in a foreseeable future.
