### ISSUE TITLE
Non-compression format for config

### ISSUE THREAD

**Issue by Desynq** [Szum123321/textile_backup#67]
When file size isn't an issue, the time required to compress backups and consequently the additional time spent uncompressing them when restoring to a backup can drag on for several seconds given larger file sizes.

An additional format option for generating uncompressed "folder" backups would be nice.

**Comment by Szum123321** [comment]
This freature is on its way.
see: 3c5976f19830f2a0c216b9ac99ad82c7acc92726

For now it simply packs files into a tarball but I may try to add an option for a folder

**Comment by Szum123321** [comment]
Added in 2.1.0
