### ISSUE TITLE
Loading Backups Cause Chunk Errors and delete progress

### ISSUE THREAD

**Issue by Karlb2222** [Szum123321/textile_backup#69]
I'm playing on 1.17 and trying to use Textile Backup to make restores in case machines don't work on the first try. When I made a backup using "backup start" then tried to reload it thirty minutes later, several of the chunks nearby, as well as unloaded chunks seemed to be completely reset, erasing a huge amount of progress. When I restored to an automatic backup from about an hour before, it still had some chunks completely reset but not as many it seemed.

**Comment by Karlb2222** [comment]
Upon further investigation, the saved backups work fine if you manually unzip the zip file and open the save, which makes me think that it's an issue with the restore function, as I'm pretty confident I'm using it correctly.

I'm not a programmer at all so this is just speculation.

**Comment by Szum123321** [comment]
Do you get any error messages?

**Comment by Karlb2222** [comment]
No error messages as far as I can tell, when I  use the restore command it warns me that the server will be restarted then kicks me out. When I load back into the world the chunks are messed up.

**Comment by Szum123321** [comment]
Probably #63
