### ISSUE TITLE
Backups have a "." directory

### ISSUE THREAD

**Issue by magneticflux-** [Szum123321/textile_backup#7]
When running backups on Windows, the zip file is created with a structure of `/\./worldname/level.dat`, where `\.` is a literal dot. Interestingly, this causes problems with Windows's extraction but not with 7‑Zip.

![image](https://user-images.githubusercontent.com/9124288/78087405-a2a8ba00-7386-11ea-8bdc-31a320eceb1b.png)

![image](https://user-images.githubusercontent.com/9124288/78087434-b3f1c680-7386-11ea-8b0a-5d09146ad182.png)

**Comment by Szum123321** [comment]
That's weird. If you cloud upload both zip and world folder that would help a lot.

**Comment by magneticflux-** [comment]
Here are zips of the "saves" folder and the "backup" folder as they appear after creating a new world and making a single backup:
[saves.zip](https://github.com/Szum123321/textile_backup/files/4413056/saves.zip)
[backup.zip](https://github.com/Szum123321/textile_backup/files/4413057/backup.zip)

**Comment by Szum123321** [comment]
Cloud you pleas share config file?

**Comment by magneticflux-** [comment]
Here is my config:
```json5
{
	/* 
	   Time between backups in seconds
	*/
	"backupInterval": 3600,
	/* 
	   Should backups be done even if there is no players?
	*/
	"doBackupsOnEmptyServer": false,
	/* 
	   Should backups be made on server shutdown
	*/
	"shutdownBackup": true,
	/* 
	   A path to backup folder
	*/
	"path": "backup/",
	/* 
	   Should every world has its won backup folder?
	*/
	"perWorldBackup": false,
	/* 
	   Maximum number of backups to keep. if 0 then no backup will be deleted based on its amount
	*/
	"backupsToKeep": 10,
	/* 
	   Maximum age of backups to keep in seconds.
	    if 0 then backups will not be deleted based on its age 
	*/
	"maxAge": 0,
	/* 
	   Maximum size of backup folder in kilo bytes. 
	*/
	"maxSize": 0,
	/* 
	   Compression level 
	   0 - 9
	*/
	"compression": 1,
	/* 
	   Print info to game out
	*/
	"log": true,
	/* 
	   Minimal permission level required to run commands
	*/
	"permissionLevel": 4,
	/* 
	   Player on singleplayer is always allowed to run command. Warning! On lan party everyone will be allowed to run it.
	*/
	"alwaysSingleplayerAllowed": true,
	/* 
	   Players allowed to run backup commands without sufficient permission level
	*/
	"whitelist": [],
	/* 
	   Players banned from running backup commands besides their sufficient permission level
	*/
	"blacklist": [],
	/* 
	   Format of date&time used to name backup files.
	*/
	"dateTimeFormat": "dd.MM.yyyy_HH-mm-ss"
}
```

**Comment by Szum123321** [comment]
I don't know what could caused that. Have you tried different versions?

**Comment by 1a2s3d4f1** [comment]
My backups have a  "."  too

**Comment by Szum123321** [comment]
Which version and on windows?

**Comment by 1a2s3d4f1** [comment]
https://github.com/Szum123321/textile_backup/blob/f8d2a69743dca7815c1a742b54435e58c99cc23e/src/main/java/net/szum123321/textile_backup/core/Compressor.java#L39

```
        try(ZipOutputStream arc = new ZipOutputStream(new FileOutputStream(out))) {
            String os = System.getProperty("os.name");
            if (os.toLowerCase().startsWith("win")) {
                arc.setLevel(TextileBackup.config.compression);
                addToArchive(arc, in, "backup");
            } else {
                arc.setLevel(TextileBackup.config.compression);
                addToArchive(arc, in, ".");
            }
        } catch (IOException e) {
            TextileBackup.logger.error(e.getMessage());
        }
```
cheak system  if system is windows Use backup replace "."
I don't know a good way to save this problem
test in textile_backup-1.0.0-1.15.2 (windows system)

**Comment by Szum123321** [comment]
Alright, I'm currently working on implementing the repair. Expect update somewhere tomorrow.

**Comment by Szum123321** [comment]
Repaired in 1.1.1.
