### ISSUE TITLE
Pause automatic backups with command

### ISSUE THREAD

**Issue by amot-dev** [Szum123321/textile_backup#75]
From what I can tell, there doesn't seem to be an option to pause backups without changing the config and restarting the server.

I often go afk overnight on my server and I don't need hourly backups during that time (plus if I only want to keep 10 backups at a time, those would be quickly overwritten). It would be cool to be able to run `/backup pause` before I go to bed and `/backup resume` in the morning.

**Comment by amot-dev** [comment]
As a bonus, it would be nice if the backup message still came up every backup interval, just to let you know backups are paused, in case you forgot to turn them back on.

**Comment by Szum123321** [comment]
There's an option to perform backups only when there are players online.

**Comment by amot-dev** [comment]
I realize that option exists, but when I afk overnight, there is a player online so it doesn't help in that case
