### ISSUE TITLE
Java Compression Library Missing

### ISSUE THREAD

**Issue by utoc** [Szum123321/textile_backup#8]
Greetings

I am running Minecraft 1.15 and Modpack All The Mods release 1.16a with addition mods ``dcintegration-1.1.14-1.15.jar`` (Discord Integration) and ``textile_backup[FORGE]-1.1.1-1.14.4.jar``.

Forge version ``forge-1.15.2-31.1.44``

Pastebin as follows: https://pastebin.com/aYLzVSWh

Java runtime as follows:
```OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

For grins I tried with a clean forge server with only textile_backup and experienced the same issue.  The full debug log available here: https://pastebin.com/tt8tSimv

**Comment by Szum123321** [comment]
I once more forgot to include one library. Fixed version should be available soon.

**Comment by Szum123321** [comment]
Resolved in 1.1.2-1.14.4.
