### ISSUE TITLE
Backup files are 1 KB (1.18.1)

### ISSUE THREAD

**Issue by pokeblokdude** [Szum123321/textile_backup#80]
Very similar issue to #20, but with a different exception.

![image](https://user-images.githubusercontent.com/61332044/147270190-912d13b2-0f8f-4db9-86a5-91be487ca192.png)

Using all default settings. One interesting thing is that the first two backups the server made were fine, but since then every backup has failed, resulting in a 1 KB empty zip file. Uncompressed world size is 964 MB. Server is running on Debian.

Other mods installed are Lithium and Starlight.

**Comment by Szum123321** [comment]
You're right that it looks very similar but appears because the tmp file system is read-only I'll add a check for that. Follow the wiki for repair

Edit: #20 was caused by a lock file having funny permissions on windows, this is related to #51 and has the same root cause

**Comment by Szum123321** [comment]
Can you tell what permission does the /tmp directory have?

**Comment by pokeblokdude** [comment]
rwxrwxrwt

**Comment by Szum123321** [comment]
That's interesting...

**Comment by Szum123321** [comment]
Ok, so I added a test to see if the tmp directory is writable, here's a test build, could you tell me if it screams at you?
[textile_backup-2.3.1-a-1.18.jar.tar.gz](https://github.com/Szum123321/textile_backup/files/7771176/textile_backup-2.3.1-a-1.18.jar.tar.gz)

**Comment by pokeblokdude** [comment]
Seems to have worked!

![image](https://user-images.githubusercontent.com/61332044/147309637-34541cfb-7dce-4ee5-8303-3ec666c47846.png)

The backup file is now ~930 MB as expected.

**Comment by pokeblokdude** [comment]
![image](https://user-images.githubusercontent.com/61332044/147309705-472df860-79ae-4b90-b50c-503141662c01.png)

Seems to have worked! The backup file is now ~930 MB, as expected.

**Comment by Szum123321** [comment]
Great!
 Keep in mind there's still something wrong with your system as java correctly detected it doesn't have the write permissions and just used slower compressor which won't use the tmp files.
