### ISSUE TITLE
Backup server when last player disconnects

### ISSUE THREAD

**Issue by CEbbinghaus** [Szum123321/textile_backup#86]
This is fairly self-explanatory.  It would be nice if there was a boolean option to backup the server when the last player disconnects. This would allow for a guaranteed state whenever the server is empty in case of a fatal crash or power outage.

**Comment by Szum123321** [comment]
Too unsafe. Malicious user could potentially clog entire server by joining in and out

**Comment by CEbbinghaus** [comment]
This can easily be mitigated by a: having it only as an option to be enabled and b: working around that by disallowing more than 1 backup in 5 minutes or so or a certain user not being able to create 2 backups in an hour.

This server is meant for friends and me so it would make it an extremely useful feature so we don't waste a whole ton of backups. Creating 1 backup when the last person leaves makes for a very easy to manage the amount of backups and guarantees that the last modified state is kept.

The idea came from Satisfactory who have recently created their own dedicated servers and honestly it is something I hadn't thought of but makes so much sense.

I don't think the argument of "could be abused" is reason enough to dismiss the entire idea when there are so many ways of working around that. (e.g minimum of 10 minutes of playtime before leaving causes a backup) And for all cases where this isn't a public server accessible to all those kinds of arguments are completely void since attackers aren't a concern. Half my friends have direct access to the server so they are able to do a whole lot worse than cause it so save a bunch of backups
