### ISSUE TITLE
The mod tells me I ran out of storage but in fact I didn't

### ISSUE THREAD

**Issue by Arcadi4** [Szum123321/textile_backup#88]
<img width="861" alt="截屏2022-02-02 14 42 38" src="https://user-images.githubusercontent.com/97033226/152106510-6cc3232d-2a0e-4188-bcaa-233dd652d85e.png">
<img width="859" alt="截屏2022-02-02 14 42 52" src="https://user-images.githubusercontent.com/97033226/152106520-a6370e59-ac77-4ad1-abd5-e89aa558582a.png">
<img width="299" alt="截屏2022-02-02 14 44 57" src="https://user-images.githubusercontent.com/97033226/152106666-6e67522b-b9a8-430a-a400-4e65db83d16c.png">

**Comment by Arcadi4** [comment]
Backup files created are 50 bytes

**Comment by Szum123321** [comment]
You ran out, just on another filesystem.
See: https://github.com/Szum123321/textile_backup/wiki/ZIP-Problems
