### ISSUE TITLE
It deleted my world when i used it

### ISSUE THREAD

**Issue by Vxbade** [Szum123321/textile_backup#91]
When I restored my world back to 3 hours before the time of restoration it deleted my hard worked on world

**Comment by wilcooo** [comment]
Same thing happened to me. You can manually unzip the backup named `#Old_World` in the `.minecraft/backup/worldname` folder into your `.minecraft/save/worldname` folder to get back to right before you initiated the restore. The backup that you actually want is probably empty though (you can check by unzipping the backup), but you might have other backups from around the same time.

**Technical details:**
- the mod worked fine for me in fabric 1.18.1. Only after updating to 1.18.2 (and also updating the other mods I use) this problem occured.
- The "faulty" backup made in this new version is only 179MB (as compared to 1.7GB for the older backups). It only contains the folders `data/`, `playerdata/` (both with contents) and the file `session.lock`.
- Edit: tried backing up & restoring again. This time it worked. Maybe it only happens the first time after updating? Or it's a fluke..

**Comment by wilcooo** [comment]
Some rudimentary checks after backing up/before restoring might prevent this.

"The backup seems to be missing files, do you want to try again?"
"The backup seems to be missing files, are you sure you want to restore?"

**Comment by eristhea** [comment]
I can confirm this still happened to me with a restore or two on 1.18.1. It's very rare though, and I've never been able to make a concrete reproduction method.

**Comment by wilcooo** [comment]
I found the following warning in the logs:
`[19:31:35] [Server thread/WARN]: [Textile Backup] Not enough space left in tmp directory!`

Changing the temporary directory (using java argument: `-Djava.io.tmpdir=/home/myname/tmp`) seems to fix the issue.

Furthermore, I noticed that either increasing the memory (using java arguments: `-Xms2048m -Xmx8192m`) makes the backup fail a lot less often.

**Comment by Szum123321** [comment]
Still related to #80
