### ISSUE TITLE
No backups when a player isn't on the server?

### ISSUE THREAD

**Issue by Scratchman** [Szum123321/textile_backup#92]
I'd like backups to be made even if nobody is on the server at the scheduled times, I've set up your mod to make a backup every 6 hours and keep 12 backups, but if no one is on the server at the scheduled times then a backup isn't made. 

I've been running my server with your mod set up this way for the last 2 days but so far it's only made 3 backups instead of 8, even with many players being logged in at various times. 

I think backups should be made if any players have logged on since the last backup was done.

**Comment by Szum123321** [comment]
Read the docs.
