### ISSUE TITLE
Backups overloading the server after the backup is done

### ISSUE THREAD

**Issue by redstonerti** [Szum123321/textile_backup#96]
Hey, I've been using your mod since 1.16.5 and I never had any problems with it. Awesome mod. Lately though, I've been having issues with my server and sometimes even internet dying because of backups. When a backup is starting and finishing, there is a huge amount of lag, like 5 seconds for one tick for finishing and maybe 2 seconds for starting. While it's doing the backup though, it's fine after I set the compression core count limit to 1.

Here is a spark profile while there were players in the server: https://spark.lucko.me/5M22SCqDBq
as you can see, the maximum mspt is very high, and that is due to backups.

This was taken when I had allocated 8GB of RAM to the server, and at this time, backups would sometimes crash the server.

I have now allocated 16GB of RAM to it, and it seems to have made the problem a bit better. I haven't got a spark profile of it yet though.

**Comment by Szum123321** [comment]
I don't think it's really fixable. Core count limit is meant to prevent exactly the thing you're describing.
